### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by gcelano** [korpling/paula-xml#2]
The link http://www.sfb632.uni-potsdam.de/images/doc/PAULA_P1.1.2013.1.21a.pdf is not working

**Comment by amir-zeldes** [comment]
Looks like the latest version online is here:

https://korpling.github.io/paula-xml/unpublished/PAULA%20XML%20Documentation.pdf

**Comment by thomaskrause** [comment]
> Looks like the latest version online is here:
> 
> https://korpling.github.io/paula-xml/unpublished/PAULA%20XML%20Documentation.pdf

This version is the compiled one from this repository. The original PDF has been moved around on the old SFB pages and seems now to be found under <http://www.sfb632.uni-potsdam.de/downloads/paula/PAULA_P1.1.2013.1.21a.pdf>

I updated the link in the README, thanks for reporting this issue!
